baseurl = "http://blog.gdggranada.com/"
languageCode = "es-ES"
title = "GDG Granada"
theme = "HugoMDL"
MetaDataFormat = "yaml"

[permalinks]
	page = "/:title/"
	about = "/:filename/"

[params]
  author = "GDG Granada"
  avatar = "/images/avatar.png"
  background = "/images/background.jpg"
  description = "Blog oficial de Google Developers Group Granada. Un lugar de encuentro para la comunidad local de desarrolladores" #meta description
  image = "/images/Logo_GDG_Granada.png" #for frontpage profile card
  mdlPrimary = "indigo"
  mdlSecondary = "pink"
  website = "gdggranada.com"
  email = "contacto@gdggranada.com"
  twitter = "https://twitter.com/GDGgranada/"
  github = "https://github.com/GDGGranada/"
  facebook = "https://www.facebook.com/GDGGranada/"
  telegram = "https://t.me/gdggranada/"
  meetup = "https://www.meetup.com/es-ES/GDG_Granada/"
  copyrightyear = "2017"
  frontpageposts = 6 #number of post cards to display on frontpage

# Fully customizable header menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Artículos"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Agenda"
  url = "/agenda/"
  weight = -160
[[menu.main]]
  name = "Patrocinadores"
  url = "/patrocinadores/"
  weight = -150
[[menu.main]]
  name = "Sobre nosotros"
  url = "/about/"
  weight = -140
